version: '3.8'

services:
  db-h2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-h2
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
